# Generated by Django 4.2.26 on 2026-01-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimentos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('PREFERENCIAL', 'Preferencial'), ('URGENTE', 'Urgente')], max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('CONVENIO', 'Convênio')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedimentos.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressao_arterial', models.CharField(max_length=10)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturacao', models.PositiveSmallIntegerField()),
                ('frequencia_cardiaca', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem', to='atendimentos.atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='atendimentos.atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='atendimentos.atendimento')),
            ],
        ),
    ]
