# Generated by Django 4.2.26 on 2026-03-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='altura',
        ),
    ]
