# Generated by Django 4.2.26 on 2026-03-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_remove_triagem_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='hora_chamada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
