# Generated by Django 4.2.26 on 2026-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_atendimento_hora_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='glicemia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
