# Generated by Django 4.2.26 on 2026-01-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='ativo',
        ),
    ]
